# Generated by Django 5.0 on 2024-01-10 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50, unique=True)),
                ('brand_image', models.ImageField(upload_to='brands/')),
                ('brand_offer', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'BRANDS',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('category_image', models.ImageField(upload_to='category/')),
                ('category_offer', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'CATEGORIES',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50)),
                ('attribute_value', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'PRODUCT ATTRIBUTES',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('base_image', models.ImageField(upload_to='products/')),
                ('description', models.TextField(default='NA')),
                ('product_offer', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.brands')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
            ],
            options={
                'verbose_name_plural': 'PRODUCTS',
            },
        ),
        migrations.CreateModel(
            name='ProductVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.products')),
                ('product_attributes', models.ManyToManyField(null=True, to='inventory.productattributes')),
            ],
            options={
                'verbose_name_plural': 'PRODUCT VARIANTS',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_imgs/')),
                ('default_img', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(to='inventory.productvariants')),
            ],
            options={
                'verbose_name_plural': 'PRODUCT IMAGES',
            },
        ),
    ]
