# Generated by Django 5.0 on 2024-01-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariants',
            name='product_attributes',
            field=models.ManyToManyField(to='inventory.productattributes'),
        ),
    ]
