# Generated by Django 5.0 on 2024-01-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_productattributes_products_productvariants_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name_plural': 'BRANDS'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'CATEGORIES'},
        ),
        migrations.AlterModelOptions(
            name='productattributes',
            options={'verbose_name_plural': 'PRODUCT ATTRIBUTES'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'PRODUCT IMAGES'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'PRODUCTS'},
        ),
        migrations.AlterModelOptions(
            name='productvariants',
            options={'verbose_name_plural': 'PRODUCT VARIANTS'},
        ),
        migrations.AddField(
            model_name='productimages',
            name='default_img',
            field=models.BooleanField(default=False),
        ),
    ]
