# Generated by Django 5.0 on 2024-01-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_productvariants_product_attributes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattributes',
            options={'ordering': ('-id',), 'verbose_name_plural': 'PRODUCT ATTRIBUTES'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('-id',), 'verbose_name_plural': 'PRODUCTS'},
        ),
        migrations.AlterModelOptions(
            name='productvariants',
            options={'ordering': ('-id',), 'verbose_name_plural': 'PRODUCT VARIANTS'},
        ),
    ]
