# Generated by Django 5.0 on 2024-01-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
