# Generated by Django 5.0 on 2024-01-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_orders_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ('-id',)},
        ),
    ]
