# Generated by Django 5.0 on 2024-01-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_orders_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='discount_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='grand_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Order Confirmed', 'Order Confirmed'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Order Cancelled', 'Order Cancelled')], default='Order Confirmed', max_length=200),
        ),
    ]
