# Generated by Django 5.0 on 2024-01-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_ordertracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoupons',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercoupons',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
